-- Insert the mandatory JSON stock from the assignment
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('67921c529506081cc0f2984d', 'Morgan PLC', 'MOR', 8185.08);

-- Insert dummy stocks to test the frontend Explore Tab pagination
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_01', 'Apple Inc', 'AAPL', 175.50);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_02', 'Microsoft Corp', 'MSFT', 315.20);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_03', 'Google LLC', 'GOOGL', 142.10);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_04', 'Amazon.com', 'AMZN', 130.00);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_05', 'Tesla Inc', 'TSLA', 250.75);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_06', 'Meta Platforms', 'META', 295.30);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_07', 'NVIDIA Corp', 'NVDA', 460.15);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_08', 'Netflix Inc', 'NFLX', 410.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_09', 'Adobe Inc', 'ADBE', 530.40);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_10', 'Intel Corp', 'INTC', 35.60);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_11', 'AMD Inc', 'AMD', 105.25);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_12', 'Spotify Tech', 'SPOT', 160.90);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_13', 'Salesforce Inc', 'CRM', 215.30);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_14', 'Oracle Corp', 'ORCL', 112.45);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_15', 'IBM Corp', 'IBM', 145.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_16', 'Cisco Systems', 'CSCO', 55.20);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_17', 'Walt Disney Co', 'DIS', 85.60);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_18', 'Nike Inc', 'NKE', 98.50);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_19', 'Coca-Cola Co', 'KO', 60.15);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_20', 'PepsiCo Inc', 'PEP', 175.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_21', 'Walmart Inc', 'WMT', 162.30);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_22', 'Target Corp', 'TGT', 125.40);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_23', 'Home Depot', 'HD', 330.10);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_24', 'Lowe''s Companies', 'LOW', 210.60);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_25', 'Procter & Gamble', 'PG', 155.90);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_26', 'Johnson & Johnson', 'JNJ', 165.25);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_27', 'Pfizer Inc', 'PFE', 35.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_28', 'Moderna Inc', 'MRNA', 105.40);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_29', 'Visa Inc', 'V', 245.15);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_30', 'Mastercard Inc', 'MA', 410.50);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_31', 'PayPal Holdings', 'PYPL', 62.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_32', 'Block Inc', 'SQ', 58.90);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_33', 'JPMorgan Chase', 'JPM', 150.30);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_34', 'Bank of America', 'BAC', 29.50);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_35', 'Wells Fargo', 'WFC', 42.10);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_36', 'Goldman Sachs', 'GS', 340.20);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_37', 'Boeing Co', 'BA', 215.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_38', 'Lockheed Martin', 'LMT', 450.60);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_39', 'Caterpillar Inc', 'CAT', 280.40);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_40', 'Deere & Company', 'DE', 410.15);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_41', 'Ford Motor Co', 'F', 12.50);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_42', 'General Motors', 'GM', 33.20);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_43', 'Toyota Motor', 'TM', 170.80);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_44', 'Honda Motor', 'HMC', 32.10);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_45', 'Exxon Mobil', 'XOM', 115.40);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_46', 'Chevron Corp', 'CVX', 160.25);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_47', 'BP plc', 'BP', 38.90);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_48', 'Shell plc', 'SHEL', 65.10);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_49', 'AT&T Inc', 'T', 15.20);
INSERT INTO stock (id, stock_name, symbol, base_price) VALUES ('stock_50', 'Verizon Comms', 'VZ', 34.50);